version: '3.3'
services:
  price-pusher:
    container_name: arbitrum-rdnt-pyth-pusher
    # Replace <version> with the latest released image of the price pusher from here:
    # https://gallery.ecr.aws/pyth-network/xc-price-pusher
    image: public.ecr.aws/pyth-network/xc-price-pusher:v6.8.0
    restart: 'no'
    entrypoint:
      sh -c "echo $MNEMONIC > /mnemonic && node lib/index.js evm --endpoint=https://arb1.arbitrum.io/rpc
      --mnemonic-file=/mnemonic --pyth-contract-address=0xff1a0f4744e8582DF1aE09D5611b887B6a12925C
      --price-service-endpoint=https://hermes.pyth.network --price-config-file=/price_config --polling-frequency=900"
    # command: |
    #   -- evm
    #   --endpoint=https://arb1.arbitrum.io/rpc
    #   --mnemonic-file=$MNEMONIC
    #   --pyth-contract-address=0xff1a0f4744e8582DF1aE09D5611b887B6a12925C
    #   --price-service-endpoint=https://hermes.pyth.network
    #   --price-config-file=/price_config
    #   --polling-frequency=900
    environment:
      - MNEMONIC=${MNEMONIC}
    volumes:
      - ./../price-config.yaml:/price_config
