version: "3.3"
services:
  price-pusher:
    container_name: ethereum-rdnt-pyth-pusher
    # Replace <version> with the latest released image of the price pusher from here:
    # https://gallery.ecr.aws/pyth-network/xc-price-pusher
    image: public.ecr.aws/pyth-network/xc-price-pusher:v6.8.0
    restart: "no"
    entrypoint: >
      sh -c "echo '${MNEMONIC}' > /tmp/mnemonic && node lib/index.js evm --endpoint=https://eth.llamarpc.com
      --mnemonic-file=/tmp/mnemonic --pyth-contract-address=0x4305FB66699C3B2702D4d05CF36551390A4c69C6
      --price-service-endpoint=https://hermes.pyth.network --price-config-file=/price_config --polling-frequency=900"
    environment:
      - MNEMONIC=${MNEMONIC}
    volumes:
      - ./../price-config.yaml:/price_config
