name: Update pyth price for arbitrum

on:
  workflow_dispatch:
  schedule:
    # Every hour
    - cron: '0 * * * *'

jobs:
  upd_pyth_prices:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      MNEMONIC: ${{ secrets.MNEMONIC }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      - name: Build docker images
        run: docker-compose -f arbitrum/docker-compose.yaml build

      - name: PS docker containers
        run: docker ps

      - name: Run price update
        run: docker-compose -f arbitrum/docker-compose.yaml up
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
